alter table organizations enable row level security;
alter table people enable row level security;
alter table person_organizations enable row level security;
alter table notes enable row level security;
alter table interactions enable row level security;
alter table crm_records enable row level security;
alter table relationships enable row level security;
alter table institution_links enable row level security;
alter table sources enable row level security;
alter table messages enable row level security;
alter table message_events enable row level security;
alter table tasks enable row level security;
alter table alerts enable row level security;

create policy "authenticated read organizations" on organizations for select to authenticated using (true);
create policy "authenticated write organizations" on organizations for all to authenticated using (true) with check (true);
create policy "authenticated read people" on people for select to authenticated using (true);
create policy "authenticated write people" on people for all to authenticated using (true) with check (true);
create policy "authenticated read person_organizations" on person_organizations for select to authenticated using (true);
create policy "authenticated write person_organizations" on person_organizations for all to authenticated using (true) with check (true);
create policy "authenticated read notes" on notes for select to authenticated using (true);
create policy "authenticated write notes" on notes for all to authenticated using (true) with check (true);
create policy "authenticated read interactions" on interactions for select to authenticated using (true);
create policy "authenticated write interactions" on interactions for all to authenticated using (true) with check (true);
create policy "authenticated read crm_records" on crm_records for select to authenticated using (true);
create policy "authenticated write crm_records" on crm_records for all to authenticated using (true) with check (true);
create policy "authenticated read relationships" on relationships for select to authenticated using (true);
create policy "authenticated write relationships" on relationships for all to authenticated using (true) with check (true);
create policy "authenticated read institution_links" on institution_links for select to authenticated using (true);
create policy "authenticated write institution_links" on institution_links for all to authenticated using (true) with check (true);
create policy "authenticated read sources" on sources for select to authenticated using (true);
create policy "authenticated write sources" on sources for all to authenticated using (true) with check (true);
create policy "authenticated read messages" on messages for select to authenticated using (true);
create policy "authenticated write messages" on messages for all to authenticated using (true) with check (true);
create policy "authenticated read message_events" on message_events for select to authenticated using (true);
create policy "authenticated write message_events" on message_events for all to authenticated using (true) with check (true);
create policy "authenticated read tasks" on tasks for select to authenticated using (true);
create policy "authenticated write tasks" on tasks for all to authenticated using (true) with check (true);
create policy "authenticated read alerts" on alerts for select to authenticated using (true);
create policy "authenticated write alerts" on alerts for all to authenticated using (true) with check (true);
